# Generated by Django 2.2.4 on 2020-05-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200504_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bios2',
            field=models.TextField(default=''),
        ),
    ]
