# Generated by Django 2.2.4 on 2020-05-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_person_bios2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='bios2',
            new_name='bio',
        ),
    ]
